<a href="https://colab.research.google.com/github/NickBoivinSlu/ores5160-2026/blob/main/week06_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

table01 = [
    {"Interaction ID": 10114, "Customer ID": 524, "Customer Name": "Bob Smith", "Customer Address": "121 abc",
     "Customer Phone": "1111111111", "Desk Staff ID": 48, "Desk Staff Name": "Sam G", "Timestamp": "20210202 0400 UTC", "Shift": 3},
    {"Interaction ID": 10115, "Customer ID": 127, "Customer Name": "Xi Huan", "Customer Address": "1411 xyz",
     "Customer Phone": "2112111111", "Desk Staff ID": 48, "Desk Staff Name": "Sam G", "Timestamp": "20210202 0412 UTC", "Shift": 3},
    {"Interaction ID": 10116, "Customer ID": 127, "Customer Name": "Xi Huan", "Customer Address": "1411 xyz",
     "Customer Phone": "2112111111", "Desk Staff ID": 17, "Desk Staff Name": "Mia Ol", "Timestamp": "20210202 0621 UTC", "Shift": 1},
    {"Interaction ID": 10117, "Customer ID": 421, "Customer Name": "Sri Lahk", "Customer Address": "13 ghi",
     "Customer Phone": "110111211", "Desk Staff ID": 17, "Desk Staff Name": "Mia Ol", "Timestamp": "20210202 0711 UTC", "Shift": 1},
    {"Interaction ID": 10118, "Customer ID": 524, "Customer Name": "Bob Smith", "Customer Address": "121 abc",
     "Customer Phone": "1111111111", "Desk Staff ID": 32, "Desk Staff Name": "Jose Pr", "Timestamp": "20210202 0932 UTC", "Shift": 1},
]

df = pd.DataFrame(table01)
df.head(6)

,Interaction ID,Customer ID,Customer Name,Customer Address,Customer Phone,Desk Staff ID,Desk Staff Name,Timestamp,Shift
0,10114,524,Bob Smith,121 abc,1111111111,48,Sam G,20210202 0400 UTC,3
1,10115,127,Xi Huan,1411 xyz,2112111111,48,Sam G,20210202 0412 UTC,3
2,10116,127,Xi Huan,1411 xyz,2112111111,17,Mia Ol,20210202 0621 UTC,1
3,10117,421,Sri Lahk,13 ghi,110111211,17,Mia Ol,20210202 0711 UTC,1
4,10118,524,Bob Smith,121 abc,1111111111,32,Jose Pr,20210202 0932 UTC,1

Q1. SELECT * FROM table01 WHERE Desk Staff ID = 17

In [ ]:
staff_id_17 = df[df["Desk Staff ID"] == 17]
staff_id_17

# for row in table01:
#   if row["Desk Staff ID"] == 17:
#     print(row)

,Interaction ID,Customer ID,Customer Name,Customer Address,Customer Phone,Desk Staff ID,Desk Staff Name,Timestamp,Shift
2,10116,127,Xi Huan,1411 xyz,2112111111,17,Mia Ol,20210202 0621 UTC,1
3,10117,421,Sri Lahk,13 ghi,110111211,17,Mia Ol,20210202 0711 UTC,1

Q2: SELECT * FROM table WHERE Desk Staff ID = 17 AND Customer ID = 127

In [ ]:
staff_id_17_customer_id_127 = df [ (df['Desk Staff ID']== 17) & ( df ['Customer ID'] == 127 ) ]
staff_id_17_customer_id_127

,Interaction ID,Customer ID,Customer Name,Customer Address,Customer Phone,Desk Staff ID,Desk Staff Name,Timestamp,Shift
2,10116,127,Xi Huan,1411 xyz,2112111111,17,Mia Ol,20210202 0621 UTC,1

Q3:SELECT * FROM table WHERE Desk Staff ID = 17 OR Customer ID = 127

In [ ]:
staff_id_17_or_customer_id_127 = df [ (df['Desk Staff ID']== 17) | ( df ['Customer ID'] == 127 ) ]
staff_id_17_or_customer_id_127

,Interaction ID,Customer ID,Customer Name,Customer Address,Customer Phone,Desk Staff ID,Desk Staff Name,Timestamp,Shift
1,10115,127,Xi Huan,1411 xyz,2112111111,48,Sam G,20210202 0412 UTC,3
2,10116,127,Xi Huan,1411 xyz,2112111111,17,Mia Ol,20210202 0621 UTC,1
3,10117,421,Sri Lahk,13 ghi,110111211,17,Mia Ol,20210202 0711 UTC,1

Q4: SELECT * FROM table WHERE NOT Desk Staff ID = 17 (HINT: use !=)

In [ ]:
staff_id_not_17 = df[ df['Desk Staff ID'] !=17 ]
staff_id_not_17

,Interaction ID,Customer ID,Customer Name,Customer Address,Customer Phone,Desk Staff ID,Desk Staff Name,Timestamp,Shift
0,10114,524,Bob Smith,121 abc,1111111111,48,Sam G,20210202 0400 UTC,3
1,10115,127,Xi Huan,1411 xyz,2112111111,48,Sam G,20210202 0412 UTC,3
4,10118,524,Bob Smith,121 abc,1111111111,32,Jose Pr,20210202 0932 UTC,1

Q5:SELECT * FROM table WHERE Desk Staff ID = 17 and not Customer ID = 127

In [ ]:
staff_17_no_customer_17 = df[ (df['Desk Staff ID'] == 17) & (df['Customer ID']!=127) ]
staff_17_no_customer_17

,Interaction ID,Customer ID,Customer Name,Customer Address,Customer Phone,Desk Staff ID,Desk Staff Name,Timestamp,Shift
3,10117,421,Sri Lahk,13 ghi,110111211,17,Mia Ol,20210202 0711 UTC,1

Q6:SELECT * FROM table WHERE Desk Staff ID = 17 or not Customer ID = 127

In [ ]:
staff_17_or_customer_127 = df [ (df['Desk Staff ID'] == 17) | (df ['Customer ID']!= 127) ]
staff_17_or_customer_127

,Interaction ID,Customer ID,Customer Name,Customer Address,Customer Phone,Desk Staff ID,Desk Staff Name,Timestamp,Shift
0,10114,524,Bob Smith,121 abc,1111111111,48,Sam G,20210202 0400 UTC,3
2,10116,127,Xi Huan,1411 xyz,2112111111,17,Mia Ol,20210202 0621 UTC,1
3,10117,421,Sri Lahk,13 ghi,110111211,17,Mia Ol,20210202 0711 UTC,1
4,10118,524,Bob Smith,121 abc,1111111111,32,Jose Pr,20210202 0932 UTC,1